### ISSUE TITLE
use URL to auto load a Tree type, e.g. https://codetree.vercel.app/#react

### ISSUE THREAD

**Issue by ngduc** [philippetedajo/codetree#43]
First, great work! Thanks for creating it.

Feature: Use URL to auto load a Tree type
For example e.g. https://codetree.vercel.app/#react will auto load into React mode.
Refresh (F5) should keep existing code and mode.

If you accept contribution, I will fork and work on this feature.

**Comment by philippetedajo** [comment]
Thank you very much, yes I accept contributors, please fork and push it to a separate branch and i will validate it

**Comment by ngduc** [comment]
Not needed as you implemented the saving feature.
